# Generated by Django 3.1.1 on 2020-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201003_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='threshold',
            field=models.IntegerField(),
        ),
    ]
