# Generated by Django 3.1.1 on 2020-10-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201003_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Add',
            new_name='add',
        ),
    ]
